using System.Diagnostics;
using System.Globalization;
using System.Text;
using TableOrderWeb.Models;

namespace TableOrderWeb.Services;

public sealed class SqlCmdMenuAdminService : IMenuAdminService
{
    private readonly IConfiguration _configuration;
    private readonly ILogger<SqlCmdMenuAdminService> _logger;

    public SqlCmdMenuAdminService(IConfiguration configuration, ILogger<SqlCmdMenuAdminService> logger)
    {
        _configuration = configuration;
        _logger = logger;
    }

    public async Task<AdminMenuPageViewModel> GetAdminMenuPageAsync(int? editItemId = null, CancellationToken cancellationToken = default)
    {
        var model = new AdminMenuPageViewModel();

        try
        {
            await EnsureMenuItemSpiceLevelColumnAsync(cancellationToken);
            var categories = await ReadCategoriesAsync(cancellationToken);
            var menuItems = await ReadMenuItemsAsync(cancellationToken);

            model.Categories = categories;
            model.MenuItems = menuItems;
            model.CategoryForm = BuildNewCategoryForm(categories);
            var editingItem = menuItems.FirstOrDefault(x => x.ItemId == editItemId);
            model.Form = editingItem is null
                ? BuildNewForm(categories, menuItems)
                : BuildForm(editingItem);

            if (editItemId.HasValue && model.Form.ItemId is null)
            {
                model.ErrorMessage = "Khong tim thay món can sua.";
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Không thể tải trang quản lý menu cho admin.");
            model.ErrorMessage = $"Không đọc được dữ liệu menu SQL. Chi tiết: {ex.Message}";
        }

        return model;
    }

    public async Task<MenuAdminOperationResult> SaveCategoryAsync(AdminCategoryFormViewModel form, CancellationToken cancellationToken = default)
    {
        try
        {
            var categoryName = form.CategoryName.Trim();
            if (string.IsNullOrWhiteSpace(categoryName))
            {
                return new MenuAdminOperationResult { ErrorMessage = "Hãy nhập tên danh mục." };
            }

            var categoryCode = string.IsNullOrWhiteSpace(form.CategoryCode)
                ? BuildCategoryCode(categoryName)
                : BuildCategoryCode(form.CategoryCode);
            if (string.IsNullOrWhiteSpace(categoryCode))
            {
                return new MenuAdminOperationResult { ErrorMessage = "Mã danh mục không hợp lệ." };
            }

            if (await CategoryCodeExistsAsync(categoryCode, cancellationToken))
            {
                return new MenuAdminOperationResult { ErrorMessage = $"Mã danh mục {categoryCode} đã tồn tại. Hãy đổi mã khác." };
            }

            var displayOrder = form.DisplayOrder <= 0
                ? await GenerateNextCategoryDisplayOrderAsync(cancellationToken)
                : form.DisplayOrder;

            var output = await ExecuteSqlAsync($@"SET NOCOUNT ON;
INSERT INTO dbo.MenuCategory (CategoryCode, CategoryName, DisplayOrder, IsActive)
VALUES ({SqlVarchar(categoryCode)}, {SqlUnicode(categoryName)}, {displayOrder}, 1);
SELECT CAST(SCOPE_IDENTITY() AS INT);", cancellationToken);
            var categoryId = ParseScalarInt(output);
            if (categoryId <= 0)
            {
                return new MenuAdminOperationResult { ErrorMessage = $"Không lưu được danh mục vào SQL Server. Kết quả SQL: {output}" };
            }

            return new MenuAdminOperationResult
            {
                Succeeded = true,
                CategoryId = categoryId,
                CategoryCode = categoryCode
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Khong the luu danh muc tu form admin.");
            return new MenuAdminOperationResult { ErrorMessage = ex.Message };
        }
    }

    public async Task<MenuAdminOperationResult> SaveMenuItemAsync(AdminMenuFormViewModel form, CancellationToken cancellationToken = default)
    {
        try
        {
            await EnsureMenuItemSpiceLevelColumnAsync(cancellationToken);
            if (form.IsSoldOut)
            {
                form.IsAvailable = false;
            }
            else if (!form.ItemId.HasValue)
            {
                form.IsAvailable = true;
            }

            if (!form.ItemId.HasValue && form.PopularityScore <= 0)
            {
                form.PopularityScore = 100;
            }

            if (!await CategoryExistsAsync(form.CategoryId, cancellationToken))
            {
                return new MenuAdminOperationResult { ErrorMessage = "Danh mục món ăn không tồn tại." };
            }

            var wasAutoGeneratedCode = string.IsNullOrWhiteSpace(form.ItemCode);
            var itemCode = await ResolveItemCodeAsync(form, cancellationToken);
            if (await ItemCodeExistsAsync(itemCode, form.ItemId, cancellationToken))
            {
                if (form.ItemId.HasValue || !wasAutoGeneratedCode)
                {
                    return new MenuAdminOperationResult { ErrorMessage = $"Mã món {itemCode} đã tồn tại. Hãy đổi sang mã khác hoặc để trống để hệ thống tự tạo mã mới." };
                }

                itemCode = await GenerateNextItemCodeAsync(form.CategoryId, cancellationToken);
            }

            var sql = form.ItemId.HasValue
                ? BuildUpdateSql(form, itemCode)
                : BuildInsertSql(form, itemCode);

            var output = await ExecuteSqlAsync(sql, cancellationToken);
            var itemId = ParseScalarInt(output);

            if (itemId <= 0)
            {
                return new MenuAdminOperationResult { ErrorMessage = $"Không lưu được món ăn vào SQL Server. Kết quả SQL: {output}" };
            }

            return new MenuAdminOperationResult
            {
                Succeeded = true,
                ItemId = itemId,
                ItemCode = itemCode
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Khong the luu món an tu form admin.");
            return new MenuAdminOperationResult { ErrorMessage = ex.Message };
        }
    }

    public async Task<MenuAdminOperationResult> DeleteMenuItemAsync(int itemId, CancellationToken cancellationToken = default)
    {
        try
        {
            var sql = $@"SET NOCOUNT ON;
DELETE FROM dbo.MenuOptionChoice
WHERE OptionGroupId IN (SELECT OptionGroupId FROM dbo.MenuOptionGroup WHERE ItemId = {itemId});
DELETE FROM dbo.MenuOptionGroup WHERE ItemId = {itemId};
DELETE FROM dbo.MenuItem WHERE ItemId = {itemId};
SELECT @@ROWCOUNT;";

            var output = await ExecuteSqlAsync(sql, cancellationToken);
            var deleted = ParseScalarInt(output);

            return deleted > 0
                ? new MenuAdminOperationResult { Succeeded = true, ItemId = itemId }
                : new MenuAdminOperationResult { ErrorMessage = "Khong tim thay món an de xoa." };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Khong the xoa món an ItemId={ItemId}", itemId);
            return new MenuAdminOperationResult { ErrorMessage = ex.Message };
        }
    }

    private async Task<List<MenuCategoryViewModel>> ReadCategoriesAsync(CancellationToken cancellationToken)
    {
        const string sql = @"SET NOCOUNT ON;
SELECT CategoryId, CategoryCode, REPLACE(CategoryName, '|', '/'), DisplayOrder
FROM dbo.MenuCategory
WHERE IsActive = 1
ORDER BY DisplayOrder, CategoryName;";

        var output = await ExecuteSqlAsync(sql, cancellationToken);
        var rows = ParseRows(output, 4);

        return rows.Select(parts => new MenuCategoryViewModel
        {
            CategoryId = int.Parse(parts[0], CultureInfo.InvariantCulture),
            CategoryCode = parts[1],
            CategoryName = parts[2],
            DisplayOrder = int.Parse(parts[3], CultureInfo.InvariantCulture)
        }).ToList();
    }

    private async Task<List<AdminMenuItemViewModel>> ReadMenuItemsAsync(CancellationToken cancellationToken)
    {
        const string sql = @"SET NOCOUNT ON;
SELECT
    i.ItemId,
    i.CategoryId,
    REPLACE(c.CategoryName, '|', '/') AS CategoryName,
    i.ItemCode,
    REPLACE(i.ItemName, '|', '/') AS ItemName,
    REPLACE(ISNULL(i.Description, N''), '|', '/') AS Description,
    i.Price,
    REPLACE(ISNULL(i.ImageUrl, N''), '|', '/') AS ImageUrl,
    i.PreparationTimeMinutes,
    CASE WHEN i.IsBestSeller = 1 THEN 1 ELSE 0 END AS IsBestSeller,
    CASE WHEN i.IsAvailable = 1 THEN 1 ELSE 0 END AS IsAvailable,
    i.PopularityScore,
    ISNULL(i.SpiceLevel, 0) AS SpiceLevel
FROM dbo.MenuItem AS i
INNER JOIN dbo.MenuCategory AS c ON c.CategoryId = i.CategoryId
ORDER BY i.ItemId DESC;";

        var output = await ExecuteSqlAsync(sql, cancellationToken);
        var rows = ParseRows(output, 13);

        return rows.Select(parts => new AdminMenuItemViewModel
        {
            ItemId = int.Parse(parts[0], CultureInfo.InvariantCulture),
            CategoryId = int.Parse(parts[1], CultureInfo.InvariantCulture),
            CategoryName = parts[2],
            ItemCode = parts[3],
            Name = parts[4],
            Description = parts[5],
            Price = decimal.Parse(parts[6], CultureInfo.InvariantCulture),
            ImageUrl = ResolveImageUrl(parts[7], parts[3]),
            PreparationTimeMinutes = int.Parse(parts[8], CultureInfo.InvariantCulture),
            IsBestSeller = parts[9] == "1",
            IsAvailable = parts[10] == "1",
            PopularityScore = int.Parse(parts[11], CultureInfo.InvariantCulture),
            SpiceLevel = int.Parse(parts[12], CultureInfo.InvariantCulture)
        }).ToList();
    }

    private async Task<bool> CategoryExistsAsync(int categoryId, CancellationToken cancellationToken)
    {
        var output = await ExecuteSqlAsync($"SET NOCOUNT ON; SELECT COUNT(1) FROM dbo.MenuCategory WHERE CategoryId = {categoryId} AND IsActive = 1;", cancellationToken);
        return ParseScalarInt(output) > 0;
    }

    private async Task<bool> CategoryCodeExistsAsync(string categoryCode, CancellationToken cancellationToken)
    {
        var output = await ExecuteSqlAsync($"SET NOCOUNT ON; SELECT COUNT(1) FROM dbo.MenuCategory WHERE CategoryCode = {SqlVarchar(categoryCode)};", cancellationToken);
        return ParseScalarInt(output) > 0;
    }

    private async Task<int> GenerateNextCategoryDisplayOrderAsync(CancellationToken cancellationToken)
    {
        var output = await ExecuteSqlAsync("SET NOCOUNT ON; SELECT ISNULL(MAX(DisplayOrder), 0) + 1 FROM dbo.MenuCategory;", cancellationToken);
        var next = ParseScalarInt(output);
        return next <= 0 ? 1 : next;
    }

    private async Task<bool> ItemCodeExistsAsync(string itemCode, int? itemId, CancellationToken cancellationToken)
    {
        var whereId = itemId.HasValue ? $" AND ItemId <> {itemId.Value}" : string.Empty;
        var output = await ExecuteSqlAsync($"SET NOCOUNT ON; SELECT COUNT(1) FROM dbo.MenuItem WHERE ItemCode = {SqlVarchar(itemCode)}{whereId};", cancellationToken);
        return ParseScalarInt(output) > 0;
    }

    private async Task<string> ResolveItemCodeAsync(AdminMenuFormViewModel form, CancellationToken cancellationToken)
    {
        var trimmed = form.ItemCode.Trim().ToUpperInvariant();
        return string.IsNullOrWhiteSpace(trimmed)
            ? await GenerateNextItemCodeAsync(form.CategoryId, cancellationToken)
            : trimmed;
    }

    private async Task<string> GenerateNextItemCodeAsync(int categoryId, CancellationToken cancellationToken)
    {
        var categoryCodeOutput = await ExecuteSqlAsync($@"SET NOCOUNT ON;
SELECT TOP 1 CategoryCode
FROM dbo.MenuCategory
WHERE CategoryId = {categoryId};", cancellationToken);
        var categoryCode = FirstOutputValue(categoryCodeOutput);
        var prefix = string.IsNullOrWhiteSpace(categoryCode)
            ? "MN"
            : new string(categoryCode.Trim().ToUpperInvariant().Where(char.IsLetterOrDigit).ToArray());
        if (string.IsNullOrWhiteSpace(prefix))
        {
            prefix = "MN";
        }

        var maxOutput = await ExecuteSqlAsync($@"SET NOCOUNT ON;
SELECT ISNULL(MAX(TRY_CONVERT(int, SUBSTRING(ItemCode, {prefix.Length + 1}, 20))), 0)
FROM dbo.MenuItem
WHERE ItemCode LIKE {SqlVarchar(prefix + "%")};", cancellationToken);
        var nextNumber = ParseScalarInt(maxOutput) + 1;

        return $"{prefix}{nextNumber:000}";
    }

    private string BuildInsertSql(AdminMenuFormViewModel form, string itemCode)
    {
        return $@"SET NOCOUNT ON;
INSERT INTO dbo.MenuItem
(
    CategoryId,
    ItemCode,
    ItemName,
    Description,
    Price,
    ImageUrl,
    PreparationTimeMinutes,
    IsBestSeller,
    IsAvailable,
    PopularityScore,
    SpiceLevel
)
VALUES
(
    {form.CategoryId},
    {SqlVarchar(itemCode)},
    {SqlUnicode(form.Name)},
    {SqlNullableUnicode(form.Description)},
    {form.Price.ToString(CultureInfo.InvariantCulture)},
    {SqlNullableUnicode(form.ImageUrl)},
    {form.PreparationTimeMinutes},
    {(form.IsBestSeller ? 1 : 0)},
    {(form.IsAvailable ? 1 : 0)},
    {form.PopularityScore},
    {ClampSpiceLevel(form.SpiceLevel)}
);
SELECT CAST(SCOPE_IDENTITY() AS INT);";
    }

    private string BuildUpdateSql(AdminMenuFormViewModel form, string itemCode)
    {
        return $@"SET NOCOUNT ON;
UPDATE dbo.MenuItem
SET
    CategoryId = {form.CategoryId},
    ItemCode = {SqlVarchar(itemCode)},
    ItemName = {SqlUnicode(form.Name)},
    Description = {SqlNullableUnicode(form.Description)},
    Price = {form.Price.ToString(CultureInfo.InvariantCulture)},
    ImageUrl = {SqlNullableUnicode(form.ImageUrl)},
    PreparationTimeMinutes = {form.PreparationTimeMinutes},
    IsBestSeller = {(form.IsBestSeller ? 1 : 0)},
    IsAvailable = {(form.IsAvailable ? 1 : 0)},
    PopularityScore = {form.PopularityScore},
    SpiceLevel = {ClampSpiceLevel(form.SpiceLevel)}
WHERE ItemId = {form.ItemId!.Value};
SELECT {form.ItemId!.Value};";
    }

    private async Task EnsureMenuItemSpiceLevelColumnAsync(CancellationToken cancellationToken)
    {
        await ExecuteSqlAsync(@"SET NOCOUNT ON;
IF COL_LENGTH('dbo.MenuItem', 'SpiceLevel') IS NULL
BEGIN
    ALTER TABLE dbo.MenuItem ADD SpiceLevel int NOT NULL CONSTRAINT DF_MenuItem_SpiceLevel DEFAULT(0);
END;", cancellationToken);
    }

    private async Task<string> ExecuteSqlAsync(string sql, CancellationToken cancellationToken)
    {
        var sqlCmdPath = _configuration["SqlMenu:SqlCmdPath"];
        var server = _configuration["SqlMenu:Server"] ?? "localhost";
        var database = _configuration["SqlMenu:Database"] ?? "TableOrderDb";

        if (string.IsNullOrWhiteSpace(sqlCmdPath) || !File.Exists(sqlCmdPath))
        {
            throw new InvalidOperationException("Không tìm thấy sqlcmd để thao tác với SQL Server.");
        }

        var tempQueryFile = Path.Combine(Path.GetTempPath(), $"menu-admin-query-{Guid.NewGuid():N}.sql");
        var tempOutputFile = Path.Combine(Path.GetTempPath(), $"menu-admin-output-{Guid.NewGuid():N}.txt");

        try
        {
            await File.WriteAllTextAsync(tempQueryFile, sql, Encoding.UTF8, cancellationToken);

            var psi = new ProcessStartInfo
            {
                FileName = sqlCmdPath,
                Arguments = $"-S {server} -d {database} -E -No -u -h -1 -s \"|\" -w 65535 -y 8000 -Y 8000 -i \"{tempQueryFile}\" -o \"{tempOutputFile}\"",
                RedirectStandardError = true,
                StandardErrorEncoding = Encoding.Unicode,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = new Process { StartInfo = psi };
            process.Start();
            var errorTask = process.StandardError.ReadToEndAsync(cancellationToken);
            await process.WaitForExitAsync(cancellationToken);

            var error = (await errorTask).Trim();
            var output = File.Exists(tempOutputFile)
                ? (await File.ReadAllTextAsync(tempOutputFile, Encoding.Unicode, cancellationToken)).Trim()
                : string.Empty;

            if (process.ExitCode != 0)
            {
                throw new InvalidOperationException(string.IsNullOrWhiteSpace(error) ? "sqlcmd trả về lỗi không xác định." : error);
            }

            return output;
        }
        finally
        {
            TryDelete(tempQueryFile);
            TryDelete(tempOutputFile);
        }
    }

    private static List<string[]> ParseRows(string output, int expectedColumns)
    {
        var rows = new List<string[]>();
        var lines = output.Replace("\r", string.Empty).Split('\n', StringSplitOptions.RemoveEmptyEntries);

        foreach (var rawLine in lines)
        {
            var line = rawLine.Trim().TrimStart('\uFEFF');
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var parts = line.Split('|').Select(static x => x.Trim()).ToArray();
            if (parts.Length < expectedColumns)
            {
                continue;
            }

            rows.Add(parts);
        }

        return rows;
    }

    private static int ParseScalarInt(string output)
    {
        var line = output.Replace("\r", string.Empty)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(static x => x.Trim().TrimStart('\uFEFF'))
            .FirstOrDefault(static x => int.TryParse(x, NumberStyles.Integer, CultureInfo.InvariantCulture, out _));

        return int.TryParse(line, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? value : 0;
    }

    private static AdminMenuFormViewModel BuildForm(AdminMenuItemViewModel? item)
    {
        if (item is null)
        {
            return new AdminMenuFormViewModel();
        }

        return new AdminMenuFormViewModel
        {
            ItemId = item.ItemId,
            CategoryId = item.CategoryId,
            ItemCode = item.ItemCode,
            Name = item.Name,
            Description = item.Description,
            Price = item.Price,
            ImageUrl = item.ImageUrl,
            PreparationTimeMinutes = item.PreparationTimeMinutes,
            PopularityScore = item.PopularityScore,
            SpiceLevel = item.SpiceLevel,
            IsBestSeller = item.IsBestSeller,
            IsAvailable = item.IsAvailable,
            IsSoldOut = !item.IsAvailable
        };
    }

    private static AdminMenuFormViewModel BuildNewForm(List<MenuCategoryViewModel> categories, List<AdminMenuItemViewModel> menuItems)
    {
        var category = categories.OrderBy(x => x.DisplayOrder).FirstOrDefault();
        var prefix = category is null
            ? "MN"
            : new string(category.CategoryCode.Trim().ToUpperInvariant().Where(char.IsLetterOrDigit).ToArray());
        if (string.IsNullOrWhiteSpace(prefix))
        {
            prefix = "MN";
        }

        var maxNumber = menuItems
            .Select(x => x.ItemCode.Trim().ToUpperInvariant())
            .Where(x => x.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            .Select(x => int.TryParse(x[prefix.Length..], NumberStyles.Integer, CultureInfo.InvariantCulture, out var number) ? number : 0)
            .DefaultIfEmpty(0)
            .Max();

        return new AdminMenuFormViewModel
        {
            CategoryId = category?.CategoryId ?? 0,
            ItemCode = $"{prefix}{maxNumber + 1:000}",
            PreparationTimeMinutes = 10,
            PopularityScore = 100,
            SpiceLevel = 0,
            IsAvailable = true
        };
    }

    private static int ClampSpiceLevel(int value) => Math.Clamp(value, 0, 5);

    private static AdminCategoryFormViewModel BuildNewCategoryForm(List<MenuCategoryViewModel> categories)
    {
        return new AdminCategoryFormViewModel
        {
            DisplayOrder = categories.Any() ? categories.Max(x => x.DisplayOrder) + 1 : 1
        };
    }

    private static string BuildCategoryCode(string value)
    {
        var normalized = value.Trim().ToUpperInvariant()
            .Replace("Đ", "D")
            .Replace("Ă", "A")
            .Replace("Â", "A")
            .Replace("Ê", "E")
            .Replace("Ô", "O")
            .Replace("Ơ", "O")
            .Replace("Ư", "U");

        var chars = normalized
            .Where(char.IsLetterOrDigit)
            .Take(30)
            .ToArray();

        return new string(chars);
    }

    private static string FirstOutputValue(string output)
    {
        return output.Replace("\r", string.Empty)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(static x => x.Trim().TrimStart('\uFEFF'))
            .FirstOrDefault(static x => !string.IsNullOrWhiteSpace(x)) ?? string.Empty;
    }

    private static string ResolveImageUrl(string? imageUrl, string itemCode)
    {
        var trimmed = imageUrl?.Trim() ?? string.Empty;
        if (!string.IsNullOrWhiteSpace(trimmed))
        {
            return trimmed;
        }

        return itemCode.ToUpperInvariant() switch
        {
            "DU001" => "/images/menu/tra-dao-cam-sa.svg",
            "MC001" => "/images/menu/lau-thai-tom-nam.svg",
            "MC002" => "/images/menu/bo-nuong-sot-tieu-den.svg",
            "TM001" => "/images/menu/banh-flan-caramel.svg",
            _ => string.Empty
        };
    }

    private static string SqlVarchar(string value) => $"'{EscapeSql(value)}'";

    private static string SqlUnicode(string value) => $"N'{EscapeSql(value)}'";

    private static string SqlNullableUnicode(string? value)
        => string.IsNullOrWhiteSpace(value) ? "NULL" : $"N'{EscapeSql(value.Trim())}'";

    private static string EscapeSql(string value) => value.Trim().Replace("'", "''");

    private static void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch
        {
        }
    }
}
